apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: haproxy-cluster-role-devops
rules:

- apiGroups: [""]
  resources: ["Configmaps"] 
  verbs:     ["get", "list", "watch", "create", "patch", "update"]

- apiGroups: [""]
  resources: ["secrets"] 
  verbs:     ["get", "list", "watch", "create", "patch", "update"]  

- apiGroups: [""]
  resources: ["endpoints"]
  verbs:     ["get", "list", "watch", "create", "patch", "update"]  

- apiGroups: [""]
  resources: ["nodes"]
  verbs:     ["get", "list", "watch", "create", "patch", "update"] 

- apiGroups: [""]
  resources: ["pods"]
  verbs:     ["get", "list", "watch", "create", "patch", "update"] 

- apiGroups: [""]
  resources: ["services"]
  verbs:     ["get", "list", "watch", "create", "patch", "update"] 

- apiGroups: [""]
  resources: ["namespaces"] 
  verbs:     ["get", "list", "watch", "create", "patch", "update"] 

- apiGroups: [""]
  resources: ["events"]
  verbs:     ["get", "list", "watch", "create", "patch", "update"]

- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs:     ["get", "list", "watch", "create", "patch", "update"]