- name: paly 1
  gather_facts: false
  hosts: web_servers
  tasks:
  - name: task1
    apt: 
      update_cache: true
        
  - name: task2
    apt: 
      name: nginx
      state: latest

  - name: task3
    copy: 
      src: ./index.html
      dest: /var/www/html/index.html

  - name: task4
    sysvinit: 
      name: nginx
      state: restarted